modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="createplus_crafting"
version="1.2.6"
displayName="CreatePlus"
displayURL="https://createplus.bbd-8.org/"
credits="Create Addon for Forge 1.20.1"
authors="KilianB."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.createplus_crafting]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration